AGGTRADE = "@aggTrade"
TRADE = "@trade" 
KLINE_= "@kline_"
TIME_INTERVAL = {"1s", "1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d", "3d", "1w", "1M"}
MINITICKER = "@miniTicker"
TICKER = "@ticker"
TICKER_ = "@ticker_" 
ARR = "@arr" 
BOOKTICKER = "@bookTicker" 
AVGPRICE = "@avgPrice"
DEPTH = "@depth"
NUMBER_INTERVAL = {"5":"5", "10":"10", "20":"20", "@100ms":"@100ms"}
SYMBOLS_USDT = {"solana":"SOLUSDT"}

COLUNMS_NAME_AGG_TRADE = {"e":"aggt_event_type", "E":"aggt_event_time", "s":"aggt_symbol", "a":"aggt_aggregate_trade_id", "p":"aggt_price", "q":"aggt_quantity", "f":"aggt_first_trade_id", "l":"aggt_last_trade_id", "T":"aggt_trade_time", "m":"aggt_is_the_buyer_market_maker", "M":"aggt_ignore"}
CONLUMS_NAME_TRADE = {"e":"trade_event_type", "E":"trade_event_time", "s":"trade_eymbol", "t":"trade_trade_id", "p":"trade_price", "q":"trade_quantity", "b":"trade_buyer_order_id", "a":"trade_seller_order_id", "T":"trade_trade_time", "m":"trade_is_the_buyer_market_maker", "M":"trade_ignore"}
CONLUMS_NAME_AVG_PRICE = {"e":"avg_price_event_type", "E":"avg_price_event_time", "s":"avg_price_symbol", "i":"avg_price_average_price_interval", "w":"avg_price_average_price", "T":"avg_price_last_trade_time"}
CONLUMS_NAME_BOOK_TICKER = {"u":"book_ticker_order_book_updateId", "s":"book_ticker_symbol", "b":"book_ticker_best_bid_price", "B":"book_ticker_best_bid_qty", "a":"book_ticker_best_ask_price", "A":"book_ticker_best_ask_qty"}
CONLUMS_NAME_KLINE_INTERVAL = {"t":"kln_int_kline_start_time", "T":"kln_int_kline_close_time", "s":"kln_int_symbol", "i":"kln_int_interval", "f":"kln_int_first_trade_id", "L":"kln_int_last_trade_id", "o":"kln_int_open_price", "c":"kln_int_close_price", "h":"kln_int_high_price", "l":"kln_int_low_price", "v":"kln_int_base_asset_volume", "n":"kln_int_number_of_trades", "x":"kln_int_is_this_kline_closed", "q":"kln_int_quote_asset_volume", "V":"kln_int_taker_buy_base_asset_volume", "Q":"kln_int_taker_buy_quote_asset_volume", "B":"kln_int_ignore"}
CONLUMS_NAME_TICKER_WINDOW = {"e":"event_type", "E":"event_time", "s":"symbol", "p":"price_change", "P":"price_change_percent", "o":"open_price", "h":"high_price", "l":"low_price", "c":"last_price", "w":"weighted_average_price", "v":"total_traded_base_asset_volume", "q":"total_traded_quote_asset_volume", "O":"statistics_open_time", "C":"statistics_close_time", "F":"first_trade_id", "L":"last_trade_id", "n":"total_number_trades"}
CONLUMS_NAME_TICKER_WINDOWS_ARR = {"e":"event_type", "E":"event_time", "s":"symbol", "p":"price_change", "P":"price_change_percent", "o":"open_price", "h":"high_price", "l":"low_price", "c":"last_price", "w":"weighted_average_price", "v":"total_traded_base_asset_volume", "q":"total_traded_quote_asset_volume", "O":"statistics_open_time", "C":"statistics_close_time", "F":"first_trade_id", "L":"last_trade_id", "n":"total_number_trades"}